name: flutter_task_manager
description: A task manager app with reminder and API integration

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  audioplayers: ^6.1.0
  path_provider: ^2.1.3
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/preview.mp3
