// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQTFxXd873Ocg6aQurjmoXXfTvVuOL6c',
    appId: '1:955358562657:web:2df62c367fd27e9a2cdd20',
    messagingSenderId: '955358562657',
    projectId: 'arundemo24-59af2',
    authDomain: 'arundemo24-59af2.firebaseapp.com',
    storageBucket: 'arundemo24-59af2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1EZ3yWLy284O5Cgixbg2WhnuG8knrR3E',
    appId: '1:955358562657:android:a79eeb63525102782cdd20',
    messagingSenderId: '955358562657',
    projectId: 'arundemo24-59af2',
    storageBucket: 'arundemo24-59af2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3l-zeso2emM2urV-jdSIbbud_K4Wvtr0',
    appId: '1:955358562657:ios:587e5ae3b26243d12cdd20',
    messagingSenderId: '955358562657',
    projectId: 'arundemo24-59af2',
    storageBucket: 'arundemo24-59af2.firebasestorage.app',
    iosBundleId: 'com.example.advtoeoNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3l-zeso2emM2urV-jdSIbbud_K4Wvtr0',
    appId: '1:955358562657:ios:587e5ae3b26243d12cdd20',
    messagingSenderId: '955358562657',
    projectId: 'arundemo24-59af2',
    storageBucket: 'arundemo24-59af2.firebasestorage.app',
    iosBundleId: 'com.example.advtoeoNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxQTFxXd873Ocg6aQurjmoXXfTvVuOL6c',
    appId: '1:955358562657:web:334a380c25cebbd32cdd20',
    messagingSenderId: '955358562657',
    projectId: 'arundemo24-59af2',
    authDomain: 'arundemo24-59af2.firebaseapp.com',
    storageBucket: 'arundemo24-59af2.firebasestorage.app',
  );
}
