// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCQeWlPRyFgc7LweIetRAaGuGbVXIuL2c',
    appId: '1:580655536166:web:7377b490ef7b6b5a016ee7',
    messagingSenderId: '580655536166',
    projectId: 'minework-6b1b9',
    authDomain: 'minework-6b1b9.firebaseapp.com',
    storageBucket: 'minework-6b1b9.firebasestorage.app',
    measurementId: 'G-VF0WE158DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMiF_VsMhYC4bfqrnx6qW8x5fbkkxfJIA',
    appId: '1:580655536166:android:284f62e90d415fa9016ee7',
    messagingSenderId: '580655536166',
    projectId: 'minework-6b1b9',
    storageBucket: 'minework-6b1b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN_7v18Uj5oFzIbPh3toFNrfr8nS9hKas',
    appId: '1:580655536166:ios:12fe41a27c7bc0d2016ee7',
    messagingSenderId: '580655536166',
    projectId: 'minework-6b1b9',
    storageBucket: 'minework-6b1b9.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN_7v18Uj5oFzIbPh3toFNrfr8nS9hKas',
    appId: '1:580655536166:ios:12fe41a27c7bc0d2016ee7',
    messagingSenderId: '580655536166',
    projectId: 'minework-6b1b9',
    storageBucket: 'minework-6b1b9.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCQeWlPRyFgc7LweIetRAaGuGbVXIuL2c',
    appId: '1:580655536166:web:4f00c04adca9bba8016ee7',
    messagingSenderId: '580655536166',
    projectId: 'minework-6b1b9',
    authDomain: 'minework-6b1b9.firebaseapp.com',
    storageBucket: 'minework-6b1b9.firebasestorage.app',
    measurementId: 'G-EWVJZB7LCJ',
  );

}